on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: applibgroup/HarmonyOsSdk@test
        with:
          who-to-greet: 'HMOS '
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: cmd
