on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: main
        uses: applibgroup/HarmonyOsSdk@test1
        with:
          who-to-greet: 'HMOS '
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: cmd
